name: Required Checks
on:
  pull_request:
jobs:
  always-fails-once:
    name: Always Fails
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 120
      - name: Fail
        if: ${{ github.run_attempt == 1 }}
        run: exit 1
      - name: Succeed
        if: ${{ github.run_attempt != 1 }}
        run: echo "Success"
  evaluate-results:
    name: Evaluate Results
    runs-on: ubuntu-latest
    needs: always-fails-once
    if: ${{ always() }}
    steps:
      - run: |
          result="${{ needs.always-fails-once.result }}"
          if [[ $result != "success" && $result != "skipped" ]]; then
            echo "One or more e2e tests have failed!"
          exit 1
          fi
          echo "e2e tests have completed successfully."
