name: Required Checks
on:
  pull_request:
jobs:
  always-fails:
    name: Always Fails
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 120
      - name: Fail
        run: exit 1
  evaluate-results:
    name: Evaluate Results
    runs-on: ubuntu-latest
    needs: always-fails
    if: ${{ always() }}
    steps:
      - run: |
          result="${{ needs.always-fails.result }}"
          if [[ $result != "success" && $result != "skipped" ]]; then
            echo "One or more e2e tests have failed!"
          exit 1
          fi
          echo "e2e tests have completed successfully."
